import { Buffer } from 'buffer'

export type EthereumProvider = { request: (args: { method: string; params?: any[] }) => Promise<any>; enable?: () => Promise<any> }
export type SolanaProvider = { isPhantom?: boolean; connect: () => Promise<{ publicKey: { toString: () => string } }>; disconnect?: () => Promise<void>; signMessage: (message: Uint8Array, display?: string) => Promise<{ signature: Uint8Array; publicKey?: any } | Uint8Array>; signAndSendTransaction: (transaction: any) => Promise<{ signature: string } | string> }

declare global { interface Window { ethereum?: EthereumProvider; solana?: SolanaProvider; backpack?: { solana?: SolanaProvider } } }

const BASE_CHAIN_ID = 8453
const BASE_CHAIN_HEX = '0x2105'
const BASE_RPC_URL = 'https://mainnet.base.org'
const SITE_URL = 'https://bttcapital.cc'
let cachedEvmProvider: EthereumProvider | null = null
let cachedSolanaProvider: SolanaProvider | null = null
const B58 = '123456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz'

function base58Encode(bytes: Uint8Array): string { let digits = [0]; for (const byte of bytes) { let carry = byte; for (let j = 0; j < digits.length; j++) { const x = digits[j] * 256 + carry; digits[j] = x % 58; carry = Math.floor(x / 58) } while (carry) { digits.push(carry % 58); carry = Math.floor(carry / 58) } } let out = ''; for (const byte of bytes) { if (byte === 0) out += '1'; else break } for (let q = digits.length - 1; q >= 0; q--) out += B58[digits[q]]; return out }
function getInjectedEvmProvider(): EthereumProvider | null { if (typeof window === 'undefined') return null; return window.ethereum || null }
function getInjectedSolanaProvider(): SolanaProvider | null { if (typeof window === 'undefined') return null; return window.solana || window.backpack?.solana || null }

async function getWalletConnectProvider(): Promise<EthereumProvider> { const projectId = process.env.NEXT_PUBLIC_WALLETCONNECT_PROJECT_ID; if (!projectId) throw new Error('Wallet EVM non disponibile da questo browser.'); const mod: any = await import('@walletconnect/ethereum-provider'); const EthereumProvider = mod.default || mod.EthereumProvider; const provider = await EthereumProvider.init({ projectId, chains: [BASE_CHAIN_ID], optionalChains: [1, 10, 56, 137, 42161, 43114, 59144, 534352, 81457], showQrModal: true, rpcMap: { [BASE_CHAIN_ID]: BASE_RPC_URL }, metadata: { name: 'BTTcapital', description: 'BTTcapital wallet execution', url: SITE_URL, icons: [`${SITE_URL}/favicon.ico`] } }); await provider.enable(); cachedEvmProvider = provider; return provider }
async function getEvmProvider(): Promise<EthereumProvider> { if (cachedEvmProvider) return cachedEvmProvider; const injected = getInjectedEvmProvider(); if (injected) { cachedEvmProvider = injected; return injected } return await getWalletConnectProvider() }
async function getSolanaProvider(): Promise<SolanaProvider> { if (cachedSolanaProvider) return cachedSolanaProvider; const injected = getInjectedSolanaProvider(); if (!injected) throw new Error('Wallet Solana non disponibile da questo browser.'); cachedSolanaProvider = injected; return injected }
function normalizeEvmAddress(value: string): string { const address = String(value || '').trim(); if (!/^0x[a-fA-F0-9]{40}$/.test(address)) throw new Error('Address EVM non valido'); return address }
function normalizeSolanaAddress(value: string): string { const address = String(value || '').trim(); if (!/^[1-9A-HJ-NP-Za-km-z]{32,44}$/.test(address)) throw new Error('Address Solana non valido'); return address }
function toPaddedUint256Hex(value: string): string { const raw = BigInt(String(value || '0')); if (raw <= 0n) throw new Error('Importo non valido'); return raw.toString(16).padStart(64, '0') }
function encodeApprove(spender: string, amountRaw: string): string { const cleanSpender = normalizeEvmAddress(spender).replace(/^0x/, '').toLowerCase(); const cleanAmount = toPaddedUint256Hex(amountRaw); return `0x095ea7b3${cleanSpender.padStart(64, '0')}${cleanAmount}` }

export async function switchToBase(provider?: EthereumProvider) { const p = provider || (await getEvmProvider()); try { await p.request({ method: 'wallet_switchEthereumChain', params: [{ chainId: BASE_CHAIN_HEX }] }) } catch (e: any) { if (Number(e?.code || 0) !== 4902) throw e; await p.request({ method: 'wallet_addEthereumChain', params: [{ chainId: BASE_CHAIN_HEX, chainName: 'Base', nativeCurrency: { name: 'Ether', symbol: 'ETH', decimals: 18 }, rpcUrls: [BASE_RPC_URL], blockExplorerUrls: ['https://basescan.org'] }] }) } }
export async function requestEvmWalletConnection() { const provider = await getEvmProvider(); await switchToBase(provider); const accounts: string[] = await provider.request({ method: 'eth_requestAccounts' }); const address = normalizeEvmAddress(accounts?.[0] || ''); const chainIdHex: string = await provider.request({ method: 'eth_chainId' }); const chainId = parseInt(chainIdHex, 16); const message = ['BTTcapital EVM wallet link', `Address: ${address}`, `Chain ID: ${chainId}`, `Timestamp: ${new Date().toISOString()}`, '', 'Firma per collegare il wallet. Non è una transazione e non sposta fondi.'].join('\n'); const signature: string = await provider.request({ method: 'personal_sign', params: [message, address] }); return { address, chainId, message, signature } }
export async function requestSolanaWalletConnection() { const provider = await getSolanaProvider(); const res = await provider.connect(); const address = normalizeSolanaAddress(res?.publicKey?.toString() || ''); const message = ['BTTcapital Solana wallet link', `Address: ${address}`, `Timestamp: ${new Date().toISOString()}`, '', 'Firma per collegare il wallet. Non è una transazione e non sposta fondi.'].join('\n'); const encoded = new TextEncoder().encode(message); const signed = await provider.signMessage(encoded, 'utf8'); const signatureBytes = signed instanceof Uint8Array ? signed : signed.signature; const signature = base58Encode(signatureBytes); return { address, message, signature } }
export async function sendErc20Approval(params: { token: string; spender: string; amountRaw: string; from: string }): Promise<string> { const provider = await getEvmProvider(); await switchToBase(provider); const tx = { from: normalizeEvmAddress(params.from), to: normalizeEvmAddress(params.token), data: encodeApprove(params.spender, params.amountRaw), value: '0x0' }; return await provider.request({ method: 'eth_sendTransaction', params: [tx] }) }
export async function sendEvmWalletTransaction(tx: any): Promise<string> { const provider = await getEvmProvider(); await switchToBase(provider); if (!tx?.to || !tx?.data) throw new Error('Transazione EVM non valida'); const cleanTx: Record<string, string> = { from: normalizeEvmAddress(tx.from), to: normalizeEvmAddress(tx.to), data: String(tx.data), value: tx.value || '0x0' }; for (const key of ['gas', 'gasPrice', 'maxFeePerGas', 'maxPriorityFeePerGas']) if (tx[key]) cleanTx[key] = String(tx[key]); return await provider.request({ method: 'eth_sendTransaction', params: [cleanTx] }) }
export async function sendSolanaSwapTransaction(swapTransactionBase64: string): Promise<string> { const provider = await getSolanaProvider(); const web3: any = await import('@solana/web3.js'); const g = globalThis as any; if (!g.Buffer) g.Buffer = Buffer; const raw = Buffer.from(swapTransactionBase64, 'base64'); const tx = web3.VersionedTransaction.deserialize(raw); const res = await provider.signAndSendTransaction(tx); return typeof res === 'string' ? res : res.signature }
